### ISSUE TITLE
[Bug Report] MPM panic when no phantom declaration for struct definition

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin#3431]
# Bug Report

**Starcoin version:**
- starcoin 1.11.10 (build:v1.11.10)
- move-package-manager 1.11.10

**Current behavior:**
mpm panic when run `mpm integration-test --ub`
```shell
$ mpm integration-test --ub
BUILDING StarcoinFramework
BUILDING starcoin-framework-commons
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/4735fa5/language/move-compiler/src/command_line/compiler.rs:462:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior:**

No panic and give more information.

**Steps to reproduce:**

1. New a folder  and write the following code in `sources/MerkleDistributor.move`, `integration-tests/merkle_distributor_test.move`, `Move.toml`
2. run `mpm integration-test --ub` or `mpm integration-test`  

**Related code:**

- sources/MerkleDistributor.move 
```Rust
address SFC {
module MerkleDistributorScripts {
    use SFC::MerkleDistributor;
    use StarcoinFramework::Account;
    public(script) fun create<T: store>(signer: signer, token_amounts: u128) {
        let tokens = Account::withdraw<T>(&signer, token_amounts);
        MerkleDistributor::create<T>(&signer, tokens);
    }
}

module MerkleDistributor {
    use StarcoinFramework::Token::{Token};

    struct MerkleDistribution<T: store> has key {
        tokens: Token<T>
    }

    /// Initialization.
    public fun create<T: store>(signer: &signer, tokens: Token<T>) {
        let distribution = MerkleDistribution<T>{
            tokens
        };
        move_to(signer, distribution);
    }
}
}
```

- integration-tests/merkle_distributor_test.move
```Rust
//# init -n test

//# faucet --addr alice

//# run --signers alice
script {
    use SFC::MerkleDistributorScripts;
    use StarcoinFramework::STC::STC;

    fun create(_signer: signer) {
        let amount: u128 = 1000000000u128;
        MerkleDistributorScripts::create<STC>(_signer, amount);
    }
}
// check: EXECUTED
```

- Move.toml

```toml
[package]
name = "starcoin-framework-commons"
version = "0.0.1"


[addresses]
StarcoinFramework = "0x1"
#TODO update publish address to official multi sign address.
SFC = "0xe69e6ca2cd09be2a8f8d6722a8a60089"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda180af40a8b3e26c0c7b548c4c290cd7e7"}

[dev-dependencies]

```
**Other information:**

When add `phantom` declaration in struct definition, then run test again, everything be OK.

```Rust
    struct MerkleDistribution<phantom T: store> has key { 
        tokens: Token<T>
    } 
```
