### ISSUE TITLE
[Bug Report] mpm integration-test failed when declare additional named addressed in `init` directive 

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin#3432]
# Bug Report

**Starcoin version:**
- starcoin 1.11.10 (build:v1.11.10)
- move-package-manager 1.11.10

**Current behavior:**
mpm integration-test failed when declare additional named addressed in `init` directive 
```shell
thread 'integration-test::address_test.move' panicked at 'Missing public key. Either add a `--public-key <priv_key>` argument to the run command, or associate an address to the name 'alice' in the init command.', vm/starcoin-transactional-test-harness/src/lib.rs:641:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test integration-test::address_test.move ... FAILED

failures:
    integration-test::address_test.move
```

**Expected behavior:**

I tried to declare additional named addressed `--addresses` as [cook-book](https://starcoinorg.github.io/starcoin-cookbook/docs/move/move-test/move-integration-test#integration-test-directives) described, but got failed.

It should be right and the specified address can be used in the integration test later.

**Steps to reproduce:**

1. New a folder  and write the following code in `integration-tests/address_test.move`, `Move.toml`
2. run  `mpm integration-test`  

**Related code:**

- integration-tests/address_test.move

```Rust
//# init -n test --addresses alice=0xAA

//# faucet --addr alice --amount 10000000000000

//# run --signers alice
script {
    use StarcoinFramework::Signer;
    use StarcoinFramework::Debug;

    fun create(_signer: signer) {
        let addr = Signer::address_of(&_signer);
        Debug::print<address>(&addr);
    }
}
```

- Move.toml

```toml
[package]
name = "starcoin-framework-commons"
version = "0.0.1"


[addresses]
StarcoinFramework = "0x1"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda180af40a8b3e26c0c7b548c4c290cd7e7"}

[dev-dependencies]
```
**Other information:**
